name: Deploy website

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:

      
  build:
    name: Build
    
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        working-directory: ./aplicacao

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Build with Maven
        run: mvn package
        
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=5lyss2s1l2ss1ndr4_Devops
